[package]
name = "reality-engine"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
wgpu = { version = "0.20", features = ["webgl"] }
log = "0.4"
console_log = "1"
wasm-bindgen-futures = "0.4"
bytemuck = { version = "1.16", features = ["derive"] }
cgmath = "0.18"

[dependencies.web-sys]
version = "0.3"
features = [
  "Document",
  "Window",
  "Element",
  "HtmlCanvasElement",
  "Event",
  "EventTarget",
  "KeyboardEvent"
]
