[package]
name = "reality-signal-server"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
tokio = { version = "1.49.0", features = ["full"] }
tokio-stream = "0.1.18"
warp = { version = "0.4.2", features = ["websocket", "server"] }
